name: RageMod
main: net.rageland.ragemod.RageMod
version: 0.1

commands:
  lot:
    description: N/A
    usage: /lot
    permission:
    permission-message: No perms to do that!
  npc:
    description: N/A
    usage: /npc
    permission:
    permission-message: No perms to do that!
  npctown:
    description: N/A
    usage: /npctown
    permission:
    permission-message: No perms to do that!
  rmdebug:
    description: N/A
    usage: /rmdebug
    permission:
    permission-message: No perms to do that!
  bounty:
    description: N/A
    usage: /bounty
    permission:
    permission-message: No perms to do that!
  compass:
    description: N/A
    usage: /compass
    permission:
    permission-message: No perms to do that!
  faction:
    description: N/A
    usage: /faction
    permission:
    permission-message: No perms to do that!
  permit:
    description: N/A
    usage: /permit
    permission:
    permission-message: No perms to do that!
  quest:
    description: N/A
    usage: /quest
    permission:
    permission-message: No perms to do that!
  rage:
    description: N/A
    usage: /rage
    permission:
    permission-message: No perms to do that!
  town:
    description: N/A
    usage: /town
    permission:
    permission-message: No perms to do that!
    
permissions:
