name: RageMod
main: net.rageland.ragemod.RageMod
version: 0.1

commands:
  lot:
    description: N/A
    usage: /lot
    permission: ragemod.lot
    permission-message: No perms to do that!
  npc:
    description: N/A
    usage: /npc
    permission: ragemod.npc
    permission-message: No perms to do that!
  npctown:
    description: N/A
    usage: /npctown
    permission: ragemod.npctown
    permission-message: No perms to do that!
  rmdebug:
    description: N/A
    usage: /rmdebug
    permission: ragemod.admin.debug
    permission-message: No perms to do that!
  bounty:
    description: N/A
    usage: /bounty
    permission: ragemod.bounty
    permission-message: No perms to do that!
  compass:
    description: N/A
    usage: /compass
    permission: ragemod.compass
    permission-message: No perms to do that!
  faction:
    description: N/A
    usage: /faction
    permission: ragemod.faction
    permission-message: No perms to do that!
  permit:
    description: N/A
    usage: /permit
    permission: ragemod.permit
    permission-message: No perms to do that!
  quest:
    description: N/A
    usage: /quest
    permission: ragemod.quest
    permission-message: No perms to do that!
  rage:
    description: N/A
    usage: /rage
    permission: ragemod.rage
    permission-message: No perms to do that!
  town:
    description: N/A
    usage: /town
    permission: ragemod.town
    permission-message: No perms to do that!
    
permissions:
  ragemod.admin:
    children: 
    - ragemod.admin.smitemobs
    - ragemod.admin.debug
  ragemod.admin.smitemobs:
  ragemod.admin.debug:
  ragemod.build:
    children:
      ragemod.build.anylot: true
      ragemod.build.anytown: true
      ragemod.build.npctown: true
      ragemod.build.capitol: true
      ragemod.build.travelzone: true
  ragemod.build.anylot:
  ragemod.build.anytown:
  ragemod.build.npctown:
  ragemod.build.capitol:
  ragemod.build.travelzone:
  ragemod.lot:
  ragemod.assign:
  ragemod.evict:
  ragemod.ismoderator:
  ragemod.permit:
    children: 
      ragemod.permit.capitol: true
  ragemod.permit.capitol:
  ragemod.npc:
  ragemod.npctown:
  ragemod.referee:
  ragemod.referee.blockpvp:
  ragemod.referee.inspectspawn:
  ragemod.bounty:
  ragemod.bounty.createsign:
  ragemod.bounty.signcreate:
  ragemod.bounty.add.global:
  ragemod.bounty.removeall:
  ragemod.compass:
  ragemod.town:
  ragemod.quest:
