name: RageMod
main: net.rageland.ragemod.RageMod
version: 0.1

dev-url: http://dev.bukkit.org/server-mods/ragemod/
website: https://github.com/RageModDevs/RageMod
database: true

commands:
  lot:
    description: N/A
    usage: /lot
    permission: ragemod.lot
    permission-message: No perms to do that!
  npc:
    description: N/A
    usage: /npc
    permission: ragemod.npc
    permission-message: No perms to do that!
  npctown:
    description: N/A
    usage: /npctown
    permission: ragemod.npctown
    permission-message: No perms to do that!
  rmdebug:
    description: N/A
    usage: /rmdebug
    permission: ragemod.admin.debug
    permission-message: No perms to do that!
  bounty:
    description: N/A
    usage: /bounty
    permission: ragemod.bounty
    permission-message: No perms to do that!
  compass:
    description: N/A
    usage: /compass
    permission: ragemod.compass
    permission-message: No perms to do that!
  faction:
    description: N/A
    usage: /faction
    permission: ragemod.faction
    permission-message: No perms to do that!
  permit:
    description: N/A
    usage: /permit
    permission: ragemod.permit
    permission-message: No perms to do that!
  quest:
    description: N/A
    usage: /quest
    permission: ragemod.quest
    permission-message: No perms to do that!
  rage:
    description: N/A
    usage: /rage
    permission: ragemod.rage
    permission-message: No perms to do that!
  town:
    description: N/A
    usage: /town
    permission: ragemod.town
    permission-message: No perms to do that!
    
permissions:
  ragemod.admin:
    children: 
    - ragemod.admin.smitemobs
    - ragemod.admin.debug
  ragemod.admin.smitemobs:
    description: TBM
  ragemod.admin.debug:
    description: TBM
  ragemod.build:
    children:
      ragemod.build.anylot: true
      ragemod.build.anytown: true
      ragemod.build.npctown: true
      ragemod.build.capitol: true
      ragemod.build.travelzone: true
  ragemod.build.anylot:
    description: TBM
  ragemod.build.anytown:
    description: TBM
  ragemod.build.npctown:
    description: TBM
  ragemod.build.capitol:
    description: TBM
  ragemod.build.travelzone:
    description: TBM
  ragemod.lot:
    description: TBM
    children:
      ragemod.lot.assign: true
      ragemod.lot.claim: true
  ragemod.lot.claim:
    description: Allows lot claiming.
  ragemod.lot.assign:
    description: TBM
  ragemod.evict:
    description: TBM
  ragemod.ismoderator:
    description: TBM
  ragemod.permit:
    description: TBM
    children: 
      ragemod.permit.capitol: true
  ragemod.permit.capitol:
    description: TBM
  ragemod.npc:
    description: TBM
    children:
      ragemod.npc.create: true
  ragemod.npc.create:
    description: Allows NPC creation.
  ragemod.npctown:
    description: TBM
    children: 
      ragemod.npctown.create: true
  ragemod.npctown.create:
    description: Allows NPCTown creation.
  ragemod.referee:
    description: TBM
  ragemod.referee.blockpvp:
    description: TBM
  ragemod.referee.inspectspawn:
    description: TBM
  ragemod.bounty:
    description: TBM
  ragemod.bounty.createsign:
    description: TBM
  ragemod.bounty.signcreate:
    description: TBM
  ragemod.bounty.add.global:
    description: TBM
  ragemod.bounty.removeall:
    description: TBM
  ragemod.compass:
    description: TBM
  ragemod.town:
    description: TBM
  ragemod.quest:
    description: TBM
  ragemod.rage:
    description: Rage command access.
