name: RageMod
main: net.rageland.ragemod.RageMod
version: 0.1
softdepend: [Spout, Vault, Citizens]
database: true
commands:
  lot:
    description: N/A
    usage: /lot
  npc:
    description: NPC
  npctown:
    description: npctown
  compass:
    description: compass
  permit:
    description: permit
  rmdebug:
    description: rmdebug
  town:
    description: town
  bounty:
    description: bounty
  home:
    description: home
  rage:
    description: rage
  faction:
    description: faction
  quest:
    description: quest